// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

// @@protoc_insertion_point(imports)

@class Alert;
@class AlertBuilder;
@class EntitySelector;
@class EntitySelectorBuilder;
@class FeedEntity;
@class FeedEntityBuilder;
@class FeedHeader;
@class FeedHeaderBuilder;
@class FeedMessage;
@class FeedMessageBuilder;
@class Position;
@class PositionBuilder;
@class TimeRange;
@class TimeRangeBuilder;
@class TranslatedString;
@class TranslatedStringBuilder;
@class TranslatedStringTranslation;
@class TranslatedStringTranslationBuilder;
@class TripDescriptor;
@class TripDescriptorBuilder;
@class TripUpdate;
@class TripUpdateBuilder;
@class TripUpdateStopTimeEvent;
@class TripUpdateStopTimeEventBuilder;
@class TripUpdateStopTimeUpdate;
@class TripUpdateStopTimeUpdateBuilder;
@class VehicleDescriptor;
@class VehicleDescriptorBuilder;
@class VehiclePosition;
@class VehiclePositionBuilder;


typedef NS_ENUM(SInt32, FeedHeaderIncrementality) {
  FeedHeaderIncrementalityFullDataset = 0,
  FeedHeaderIncrementalityDifferential = 1,
};

BOOL FeedHeaderIncrementalityIsValidValue(FeedHeaderIncrementality value);
NSString *NSStringFromFeedHeaderIncrementality(FeedHeaderIncrementality value);

typedef NS_ENUM(SInt32, TripUpdateStopTimeUpdateScheduleRelationship) {
  TripUpdateStopTimeUpdateScheduleRelationshipScheduled = 0,
  TripUpdateStopTimeUpdateScheduleRelationshipSkipped = 1,
  TripUpdateStopTimeUpdateScheduleRelationshipNoData = 2,
};

BOOL TripUpdateStopTimeUpdateScheduleRelationshipIsValidValue(TripUpdateStopTimeUpdateScheduleRelationship value);
NSString *NSStringFromTripUpdateStopTimeUpdateScheduleRelationship(TripUpdateStopTimeUpdateScheduleRelationship value);

typedef NS_ENUM(SInt32, VehiclePositionVehicleStopStatus) {
  VehiclePositionVehicleStopStatusIncomingAt = 0,
  VehiclePositionVehicleStopStatusStoppedAt = 1,
  VehiclePositionVehicleStopStatusInTransitTo = 2,
};

BOOL VehiclePositionVehicleStopStatusIsValidValue(VehiclePositionVehicleStopStatus value);
NSString *NSStringFromVehiclePositionVehicleStopStatus(VehiclePositionVehicleStopStatus value);

typedef NS_ENUM(SInt32, VehiclePositionCongestionLevel) {
  VehiclePositionCongestionLevelUnknownCongestionLevel = 0,
  VehiclePositionCongestionLevelRunningSmoothly = 1,
  VehiclePositionCongestionLevelStopAndGo = 2,
  VehiclePositionCongestionLevelCongestion = 3,
  VehiclePositionCongestionLevelSevereCongestion = 4,
};

BOOL VehiclePositionCongestionLevelIsValidValue(VehiclePositionCongestionLevel value);
NSString *NSStringFromVehiclePositionCongestionLevel(VehiclePositionCongestionLevel value);

typedef NS_ENUM(SInt32, VehiclePositionOccupancyStatus) {
  VehiclePositionOccupancyStatusEmpty = 0,
  VehiclePositionOccupancyStatusManySeatsAvailable = 1,
  VehiclePositionOccupancyStatusFewSeatsAvailable = 2,
  VehiclePositionOccupancyStatusStandingRoomOnly = 3,
  VehiclePositionOccupancyStatusCrushedStandingRoomOnly = 4,
  VehiclePositionOccupancyStatusFull = 5,
  VehiclePositionOccupancyStatusNotAcceptingPassengers = 6,
};

BOOL VehiclePositionOccupancyStatusIsValidValue(VehiclePositionOccupancyStatus value);
NSString *NSStringFromVehiclePositionOccupancyStatus(VehiclePositionOccupancyStatus value);

typedef NS_ENUM(SInt32, AlertCause) {
  AlertCauseUnknownCause = 1,
  AlertCauseOtherCause = 2,
  AlertCauseTechnicalProblem = 3,
  AlertCauseStrike = 4,
  AlertCauseDemonstration = 5,
  AlertCauseAccident = 6,
  AlertCauseHoliday = 7,
  AlertCauseWeather = 8,
  AlertCauseMaintenance = 9,
  AlertCauseConstruction = 10,
  AlertCausePoliceActivity = 11,
  AlertCauseMedicalEmergency = 12,
};

BOOL AlertCauseIsValidValue(AlertCause value);
NSString *NSStringFromAlertCause(AlertCause value);

typedef NS_ENUM(SInt32, AlertEffect) {
  AlertEffectNoService = 1,
  AlertEffectReducedService = 2,
  AlertEffectSignificantDelays = 3,
  AlertEffectDetour = 4,
  AlertEffectAdditionalService = 5,
  AlertEffectModifiedService = 6,
  AlertEffectOtherEffect = 7,
  AlertEffectUnknownEffect = 8,
  AlertEffectStopMoved = 9,
};

BOOL AlertEffectIsValidValue(AlertEffect value);
NSString *NSStringFromAlertEffect(AlertEffect value);

typedef NS_ENUM(SInt32, TripDescriptorScheduleRelationship) {
  TripDescriptorScheduleRelationshipScheduled = 0,
  TripDescriptorScheduleRelationshipAdded = 1,
  TripDescriptorScheduleRelationshipUnscheduled = 2,
  TripDescriptorScheduleRelationshipCanceled = 3,
};

BOOL TripDescriptorScheduleRelationshipIsValidValue(TripDescriptorScheduleRelationship value);
NSString *NSStringFromTripDescriptorScheduleRelationship(TripDescriptorScheduleRelationship value);


@interface GtfsRealtimeRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define FeedMessage_header @"header"
#define FeedMessage_entity @"entity"
@interface FeedMessage : PBExtendableMessage<GeneratedMessageProtocol> {
@private
  BOOL hasHeader_:1;
  FeedHeader* header;
  NSMutableArray * entityArray;
}
- (BOOL) hasHeader;
@property (readonly, strong) FeedHeader* header;
@property (readonly, strong) NSArray * entity;
- (FeedEntity*)entityAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (FeedMessageBuilder*) builder;
+ (FeedMessageBuilder*) builder;
+ (FeedMessageBuilder*) builderWithPrototype:(FeedMessage*) prototype;
- (FeedMessageBuilder*) toBuilder;

+ (FeedMessage*) parseFromData:(NSData*) data;
+ (FeedMessage*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FeedMessage*) parseFromInputStream:(NSInputStream*) input;
+ (FeedMessage*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FeedMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (FeedMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface FeedMessageBuilder : PBExtendableMessageBuilder {
@private
  FeedMessage* resultFeedMessage;
}

- (FeedMessage*) defaultInstance;

- (FeedMessageBuilder*) clear;
- (FeedMessageBuilder*) clone;

- (FeedMessage*) build;
- (FeedMessage*) buildPartial;

- (FeedMessageBuilder*) mergeFrom:(FeedMessage*) other;
- (FeedMessageBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (FeedMessageBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasHeader;
- (FeedHeader*) header;
- (FeedMessageBuilder*) setHeader:(FeedHeader*) value;
- (FeedMessageBuilder*) setHeaderBuilder:(FeedHeaderBuilder*) builderForValue;
- (FeedMessageBuilder*) mergeHeader:(FeedHeader*) value;
- (FeedMessageBuilder*) clearHeader;

- (NSMutableArray *)entity;
- (FeedEntity*)entityAtIndex:(NSUInteger)index;
- (FeedMessageBuilder *)addEntity:(FeedEntity*)value;
- (FeedMessageBuilder *)setEntityArray:(NSArray *)array;
- (FeedMessageBuilder *)clearEntity;
@end

#define FeedHeader_gtfs_realtime_version @"gtfsRealtimeVersion"
#define FeedHeader_incrementality @"incrementality"
#define FeedHeader_timestamp @"timestamp"
@interface FeedHeader : PBExtendableMessage<GeneratedMessageProtocol> {
@private
  BOOL hasTimestamp_:1;
  BOOL hasGtfsRealtimeVersion_:1;
  BOOL hasIncrementality_:1;
  UInt64 timestamp;
  NSString* gtfsRealtimeVersion;
  FeedHeaderIncrementality incrementality;
}
- (BOOL) hasGtfsRealtimeVersion;
- (BOOL) hasIncrementality;
- (BOOL) hasTimestamp;
@property (readonly, strong) NSString* gtfsRealtimeVersion;
@property (readonly) FeedHeaderIncrementality incrementality;
@property (readonly) UInt64 timestamp;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (FeedHeaderBuilder*) builder;
+ (FeedHeaderBuilder*) builder;
+ (FeedHeaderBuilder*) builderWithPrototype:(FeedHeader*) prototype;
- (FeedHeaderBuilder*) toBuilder;

+ (FeedHeader*) parseFromData:(NSData*) data;
+ (FeedHeader*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FeedHeader*) parseFromInputStream:(NSInputStream*) input;
+ (FeedHeader*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FeedHeader*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (FeedHeader*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface FeedHeaderBuilder : PBExtendableMessageBuilder {
@private
  FeedHeader* resultFeedHeader;
}

- (FeedHeader*) defaultInstance;

- (FeedHeaderBuilder*) clear;
- (FeedHeaderBuilder*) clone;

- (FeedHeader*) build;
- (FeedHeader*) buildPartial;

- (FeedHeaderBuilder*) mergeFrom:(FeedHeader*) other;
- (FeedHeaderBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (FeedHeaderBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasGtfsRealtimeVersion;
- (NSString*) gtfsRealtimeVersion;
- (FeedHeaderBuilder*) setGtfsRealtimeVersion:(NSString*) value;
- (FeedHeaderBuilder*) clearGtfsRealtimeVersion;

- (BOOL) hasIncrementality;
- (FeedHeaderIncrementality) incrementality;
- (FeedHeaderBuilder*) setIncrementality:(FeedHeaderIncrementality) value;
- (FeedHeaderBuilder*) clearIncrementality;

- (BOOL) hasTimestamp;
- (UInt64) timestamp;
- (FeedHeaderBuilder*) setTimestamp:(UInt64) value;
- (FeedHeaderBuilder*) clearTimestamp;
@end

#define FeedEntity_id @"id"
#define FeedEntity_is_deleted @"isDeleted"
#define FeedEntity_trip_update @"tripUpdate"
#define FeedEntity_vehicle @"vehicle"
#define FeedEntity_alert @"alert"
@interface FeedEntity : PBExtendableMessage<GeneratedMessageProtocol> {
@private
  BOOL hasIsDeleted_:1;
  BOOL hasId_:1;
  BOOL hasTripUpdate_:1;
  BOOL hasVehicle_:1;
  BOOL hasAlert_:1;
  BOOL isDeleted_:1;
  NSString* id;
  TripUpdate* tripUpdate;
  VehiclePosition* vehicle;
  Alert* alert;
}
- (BOOL) hasId;
- (BOOL) hasIsDeleted;
- (BOOL) hasTripUpdate;
- (BOOL) hasVehicle;
- (BOOL) hasAlert;
@property (readonly, strong) NSString* id;
- (BOOL) isDeleted;
@property (readonly, strong) TripUpdate* tripUpdate;
@property (readonly, strong) VehiclePosition* vehicle;
@property (readonly, strong) Alert* alert;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (FeedEntityBuilder*) builder;
+ (FeedEntityBuilder*) builder;
+ (FeedEntityBuilder*) builderWithPrototype:(FeedEntity*) prototype;
- (FeedEntityBuilder*) toBuilder;

+ (FeedEntity*) parseFromData:(NSData*) data;
+ (FeedEntity*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FeedEntity*) parseFromInputStream:(NSInputStream*) input;
+ (FeedEntity*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FeedEntity*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (FeedEntity*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface FeedEntityBuilder : PBExtendableMessageBuilder {
@private
  FeedEntity* resultFeedEntity;
}

- (FeedEntity*) defaultInstance;

- (FeedEntityBuilder*) clear;
- (FeedEntityBuilder*) clone;

- (FeedEntity*) build;
- (FeedEntity*) buildPartial;

- (FeedEntityBuilder*) mergeFrom:(FeedEntity*) other;
- (FeedEntityBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (FeedEntityBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (NSString*) id;
- (FeedEntityBuilder*) setId:(NSString*) value;
- (FeedEntityBuilder*) clearId;

- (BOOL) hasIsDeleted;
- (BOOL) isDeleted;
- (FeedEntityBuilder*) setIsDeleted:(BOOL) value;
- (FeedEntityBuilder*) clearIsDeleted;

- (BOOL) hasTripUpdate;
- (TripUpdate*) tripUpdate;
- (FeedEntityBuilder*) setTripUpdate:(TripUpdate*) value;
- (FeedEntityBuilder*) setTripUpdateBuilder:(TripUpdateBuilder*) builderForValue;
- (FeedEntityBuilder*) mergeTripUpdate:(TripUpdate*) value;
- (FeedEntityBuilder*) clearTripUpdate;

- (BOOL) hasVehicle;
- (VehiclePosition*) vehicle;
- (FeedEntityBuilder*) setVehicle:(VehiclePosition*) value;
- (FeedEntityBuilder*) setVehicleBuilder:(VehiclePositionBuilder*) builderForValue;
- (FeedEntityBuilder*) mergeVehicle:(VehiclePosition*) value;
- (FeedEntityBuilder*) clearVehicle;

- (BOOL) hasAlert;
- (Alert*) alert;
- (FeedEntityBuilder*) setAlert:(Alert*) value;
- (FeedEntityBuilder*) setAlertBuilder:(AlertBuilder*) builderForValue;
- (FeedEntityBuilder*) mergeAlert:(Alert*) value;
- (FeedEntityBuilder*) clearAlert;
@end

#define TripUpdate_trip @"trip"
#define TripUpdate_vehicle @"vehicle"
#define TripUpdate_stop_time_update @"stopTimeUpdate"
#define TripUpdate_timestamp @"timestamp"
#define TripUpdate_delay @"delay"
@interface TripUpdate : PBExtendableMessage<GeneratedMessageProtocol> {
@private
  BOOL hasTimestamp_:1;
  BOOL hasDelay_:1;
  BOOL hasTrip_:1;
  BOOL hasVehicle_:1;
  UInt64 timestamp;
  SInt32 delay;
  TripDescriptor* trip;
  VehicleDescriptor* vehicle;
  NSMutableArray * stopTimeUpdateArray;
}
- (BOOL) hasTrip;
- (BOOL) hasVehicle;
- (BOOL) hasTimestamp;
- (BOOL) hasDelay;
@property (readonly, strong) TripDescriptor* trip;
@property (readonly, strong) VehicleDescriptor* vehicle;
@property (readonly, strong) NSArray * stopTimeUpdate;
@property (readonly) UInt64 timestamp;
@property (readonly) SInt32 delay;
- (TripUpdateStopTimeUpdate*)stopTimeUpdateAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (TripUpdateBuilder*) builder;
+ (TripUpdateBuilder*) builder;
+ (TripUpdateBuilder*) builderWithPrototype:(TripUpdate*) prototype;
- (TripUpdateBuilder*) toBuilder;

+ (TripUpdate*) parseFromData:(NSData*) data;
+ (TripUpdate*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TripUpdate*) parseFromInputStream:(NSInputStream*) input;
+ (TripUpdate*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TripUpdate*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (TripUpdate*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

#define StopTimeEvent_delay @"delay"
#define StopTimeEvent_time @"time"
#define StopTimeEvent_uncertainty @"uncertainty"
@interface TripUpdateStopTimeEvent : PBExtendableMessage<GeneratedMessageProtocol> {
@private
  BOOL hasTime_:1;
  BOOL hasDelay_:1;
  BOOL hasUncertainty_:1;
  SInt64 time;
  SInt32 delay;
  SInt32 uncertainty;
}
- (BOOL) hasDelay;
- (BOOL) hasTime;
- (BOOL) hasUncertainty;
@property (readonly) SInt32 delay;
@property (readonly) SInt64 time;
@property (readonly) SInt32 uncertainty;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (TripUpdateStopTimeEventBuilder*) builder;
+ (TripUpdateStopTimeEventBuilder*) builder;
+ (TripUpdateStopTimeEventBuilder*) builderWithPrototype:(TripUpdateStopTimeEvent*) prototype;
- (TripUpdateStopTimeEventBuilder*) toBuilder;

+ (TripUpdateStopTimeEvent*) parseFromData:(NSData*) data;
+ (TripUpdateStopTimeEvent*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TripUpdateStopTimeEvent*) parseFromInputStream:(NSInputStream*) input;
+ (TripUpdateStopTimeEvent*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TripUpdateStopTimeEvent*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (TripUpdateStopTimeEvent*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface TripUpdateStopTimeEventBuilder : PBExtendableMessageBuilder {
@private
  TripUpdateStopTimeEvent* resultStopTimeEvent;
}

- (TripUpdateStopTimeEvent*) defaultInstance;

- (TripUpdateStopTimeEventBuilder*) clear;
- (TripUpdateStopTimeEventBuilder*) clone;

- (TripUpdateStopTimeEvent*) build;
- (TripUpdateStopTimeEvent*) buildPartial;

- (TripUpdateStopTimeEventBuilder*) mergeFrom:(TripUpdateStopTimeEvent*) other;
- (TripUpdateStopTimeEventBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (TripUpdateStopTimeEventBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasDelay;
- (SInt32) delay;
- (TripUpdateStopTimeEventBuilder*) setDelay:(SInt32) value;
- (TripUpdateStopTimeEventBuilder*) clearDelay;

- (BOOL) hasTime;
- (SInt64) time;
- (TripUpdateStopTimeEventBuilder*) setTime:(SInt64) value;
- (TripUpdateStopTimeEventBuilder*) clearTime;

- (BOOL) hasUncertainty;
- (SInt32) uncertainty;
- (TripUpdateStopTimeEventBuilder*) setUncertainty:(SInt32) value;
- (TripUpdateStopTimeEventBuilder*) clearUncertainty;
@end

#define StopTimeUpdate_stop_sequence @"stopSequence"
#define StopTimeUpdate_stop_id @"stopId"
#define StopTimeUpdate_arrival @"arrival"
#define StopTimeUpdate_departure @"departure"
#define StopTimeUpdate_schedule_relationship @"scheduleRelationship"
@interface TripUpdateStopTimeUpdate : PBExtendableMessage<GeneratedMessageProtocol> {
@private
  BOOL hasStopId_:1;
  BOOL hasArrival_:1;
  BOOL hasDeparture_:1;
  BOOL hasStopSequence_:1;
  BOOL hasScheduleRelationship_:1;
  NSString* stopId;
  TripUpdateStopTimeEvent* arrival;
  TripUpdateStopTimeEvent* departure;
  UInt32 stopSequence;
  TripUpdateStopTimeUpdateScheduleRelationship scheduleRelationship;
}
- (BOOL) hasStopSequence;
- (BOOL) hasStopId;
- (BOOL) hasArrival;
- (BOOL) hasDeparture;
- (BOOL) hasScheduleRelationship;
@property (readonly) UInt32 stopSequence;
@property (readonly, strong) NSString* stopId;
@property (readonly, strong) TripUpdateStopTimeEvent* arrival;
@property (readonly, strong) TripUpdateStopTimeEvent* departure;
@property (readonly) TripUpdateStopTimeUpdateScheduleRelationship scheduleRelationship;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (TripUpdateStopTimeUpdateBuilder*) builder;
+ (TripUpdateStopTimeUpdateBuilder*) builder;
+ (TripUpdateStopTimeUpdateBuilder*) builderWithPrototype:(TripUpdateStopTimeUpdate*) prototype;
- (TripUpdateStopTimeUpdateBuilder*) toBuilder;

+ (TripUpdateStopTimeUpdate*) parseFromData:(NSData*) data;
+ (TripUpdateStopTimeUpdate*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TripUpdateStopTimeUpdate*) parseFromInputStream:(NSInputStream*) input;
+ (TripUpdateStopTimeUpdate*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TripUpdateStopTimeUpdate*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (TripUpdateStopTimeUpdate*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface TripUpdateStopTimeUpdateBuilder : PBExtendableMessageBuilder {
@private
  TripUpdateStopTimeUpdate* resultStopTimeUpdate;
}

- (TripUpdateStopTimeUpdate*) defaultInstance;

- (TripUpdateStopTimeUpdateBuilder*) clear;
- (TripUpdateStopTimeUpdateBuilder*) clone;

- (TripUpdateStopTimeUpdate*) build;
- (TripUpdateStopTimeUpdate*) buildPartial;

- (TripUpdateStopTimeUpdateBuilder*) mergeFrom:(TripUpdateStopTimeUpdate*) other;
- (TripUpdateStopTimeUpdateBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (TripUpdateStopTimeUpdateBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasStopSequence;
- (UInt32) stopSequence;
- (TripUpdateStopTimeUpdateBuilder*) setStopSequence:(UInt32) value;
- (TripUpdateStopTimeUpdateBuilder*) clearStopSequence;

- (BOOL) hasStopId;
- (NSString*) stopId;
- (TripUpdateStopTimeUpdateBuilder*) setStopId:(NSString*) value;
- (TripUpdateStopTimeUpdateBuilder*) clearStopId;

- (BOOL) hasArrival;
- (TripUpdateStopTimeEvent*) arrival;
- (TripUpdateStopTimeUpdateBuilder*) setArrival:(TripUpdateStopTimeEvent*) value;
- (TripUpdateStopTimeUpdateBuilder*) setArrivalBuilder:(TripUpdateStopTimeEventBuilder*) builderForValue;
- (TripUpdateStopTimeUpdateBuilder*) mergeArrival:(TripUpdateStopTimeEvent*) value;
- (TripUpdateStopTimeUpdateBuilder*) clearArrival;

- (BOOL) hasDeparture;
- (TripUpdateStopTimeEvent*) departure;
- (TripUpdateStopTimeUpdateBuilder*) setDeparture:(TripUpdateStopTimeEvent*) value;
- (TripUpdateStopTimeUpdateBuilder*) setDepartureBuilder:(TripUpdateStopTimeEventBuilder*) builderForValue;
- (TripUpdateStopTimeUpdateBuilder*) mergeDeparture:(TripUpdateStopTimeEvent*) value;
- (TripUpdateStopTimeUpdateBuilder*) clearDeparture;

- (BOOL) hasScheduleRelationship;
- (TripUpdateStopTimeUpdateScheduleRelationship) scheduleRelationship;
- (TripUpdateStopTimeUpdateBuilder*) setScheduleRelationship:(TripUpdateStopTimeUpdateScheduleRelationship) value;
- (TripUpdateStopTimeUpdateBuilder*) clearScheduleRelationship;
@end

@interface TripUpdateBuilder : PBExtendableMessageBuilder {
@private
  TripUpdate* resultTripUpdate;
}

- (TripUpdate*) defaultInstance;

- (TripUpdateBuilder*) clear;
- (TripUpdateBuilder*) clone;

- (TripUpdate*) build;
- (TripUpdate*) buildPartial;

- (TripUpdateBuilder*) mergeFrom:(TripUpdate*) other;
- (TripUpdateBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (TripUpdateBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasTrip;
- (TripDescriptor*) trip;
- (TripUpdateBuilder*) setTrip:(TripDescriptor*) value;
- (TripUpdateBuilder*) setTripBuilder:(TripDescriptorBuilder*) builderForValue;
- (TripUpdateBuilder*) mergeTrip:(TripDescriptor*) value;
- (TripUpdateBuilder*) clearTrip;

- (BOOL) hasVehicle;
- (VehicleDescriptor*) vehicle;
- (TripUpdateBuilder*) setVehicle:(VehicleDescriptor*) value;
- (TripUpdateBuilder*) setVehicleBuilder:(VehicleDescriptorBuilder*) builderForValue;
- (TripUpdateBuilder*) mergeVehicle:(VehicleDescriptor*) value;
- (TripUpdateBuilder*) clearVehicle;

- (NSMutableArray *)stopTimeUpdate;
- (TripUpdateStopTimeUpdate*)stopTimeUpdateAtIndex:(NSUInteger)index;
- (TripUpdateBuilder *)addStopTimeUpdate:(TripUpdateStopTimeUpdate*)value;
- (TripUpdateBuilder *)setStopTimeUpdateArray:(NSArray *)array;
- (TripUpdateBuilder *)clearStopTimeUpdate;

- (BOOL) hasTimestamp;
- (UInt64) timestamp;
- (TripUpdateBuilder*) setTimestamp:(UInt64) value;
- (TripUpdateBuilder*) clearTimestamp;

- (BOOL) hasDelay;
- (SInt32) delay;
- (TripUpdateBuilder*) setDelay:(SInt32) value;
- (TripUpdateBuilder*) clearDelay;
@end

#define VehiclePosition_trip @"trip"
#define VehiclePosition_vehicle @"vehicle"
#define VehiclePosition_position @"position"
#define VehiclePosition_current_stop_sequence @"currentStopSequence"
#define VehiclePosition_stop_id @"stopId"
#define VehiclePosition_current_status @"currentStatus"
#define VehiclePosition_timestamp @"timestamp"
#define VehiclePosition_congestion_level @"congestionLevel"
#define VehiclePosition_occupancy_status @"occupancyStatus"
@interface VehiclePosition : PBExtendableMessage<GeneratedMessageProtocol> {
@private
  BOOL hasTimestamp_:1;
  BOOL hasStopId_:1;
  BOOL hasTrip_:1;
  BOOL hasVehicle_:1;
  BOOL hasPosition_:1;
  BOOL hasCurrentStopSequence_:1;
  BOOL hasCurrentStatus_:1;
  BOOL hasCongestionLevel_:1;
  BOOL hasOccupancyStatus_:1;
  UInt64 timestamp;
  NSString* stopId;
  TripDescriptor* trip;
  VehicleDescriptor* vehicle;
  Position* position;
  UInt32 currentStopSequence;
  VehiclePositionVehicleStopStatus currentStatus;
  VehiclePositionCongestionLevel congestionLevel;
  VehiclePositionOccupancyStatus occupancyStatus;
}
- (BOOL) hasTrip;
- (BOOL) hasVehicle;
- (BOOL) hasPosition;
- (BOOL) hasCurrentStopSequence;
- (BOOL) hasStopId;
- (BOOL) hasCurrentStatus;
- (BOOL) hasTimestamp;
- (BOOL) hasCongestionLevel;
- (BOOL) hasOccupancyStatus;
@property (readonly, strong) TripDescriptor* trip;
@property (readonly, strong) VehicleDescriptor* vehicle;
@property (readonly, strong) Position* position;
@property (readonly) UInt32 currentStopSequence;
@property (readonly, strong) NSString* stopId;
@property (readonly) VehiclePositionVehicleStopStatus currentStatus;
@property (readonly) UInt64 timestamp;
@property (readonly) VehiclePositionCongestionLevel congestionLevel;
@property (readonly) VehiclePositionOccupancyStatus occupancyStatus;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (VehiclePositionBuilder*) builder;
+ (VehiclePositionBuilder*) builder;
+ (VehiclePositionBuilder*) builderWithPrototype:(VehiclePosition*) prototype;
- (VehiclePositionBuilder*) toBuilder;

+ (VehiclePosition*) parseFromData:(NSData*) data;
+ (VehiclePosition*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (VehiclePosition*) parseFromInputStream:(NSInputStream*) input;
+ (VehiclePosition*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (VehiclePosition*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (VehiclePosition*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface VehiclePositionBuilder : PBExtendableMessageBuilder {
@private
  VehiclePosition* resultVehiclePosition;
}

- (VehiclePosition*) defaultInstance;

- (VehiclePositionBuilder*) clear;
- (VehiclePositionBuilder*) clone;

- (VehiclePosition*) build;
- (VehiclePosition*) buildPartial;

- (VehiclePositionBuilder*) mergeFrom:(VehiclePosition*) other;
- (VehiclePositionBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (VehiclePositionBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasTrip;
- (TripDescriptor*) trip;
- (VehiclePositionBuilder*) setTrip:(TripDescriptor*) value;
- (VehiclePositionBuilder*) setTripBuilder:(TripDescriptorBuilder*) builderForValue;
- (VehiclePositionBuilder*) mergeTrip:(TripDescriptor*) value;
- (VehiclePositionBuilder*) clearTrip;

- (BOOL) hasVehicle;
- (VehicleDescriptor*) vehicle;
- (VehiclePositionBuilder*) setVehicle:(VehicleDescriptor*) value;
- (VehiclePositionBuilder*) setVehicleBuilder:(VehicleDescriptorBuilder*) builderForValue;
- (VehiclePositionBuilder*) mergeVehicle:(VehicleDescriptor*) value;
- (VehiclePositionBuilder*) clearVehicle;

- (BOOL) hasPosition;
- (Position*) position;
- (VehiclePositionBuilder*) setPosition:(Position*) value;
- (VehiclePositionBuilder*) setPositionBuilder:(PositionBuilder*) builderForValue;
- (VehiclePositionBuilder*) mergePosition:(Position*) value;
- (VehiclePositionBuilder*) clearPosition;

- (BOOL) hasCurrentStopSequence;
- (UInt32) currentStopSequence;
- (VehiclePositionBuilder*) setCurrentStopSequence:(UInt32) value;
- (VehiclePositionBuilder*) clearCurrentStopSequence;

- (BOOL) hasStopId;
- (NSString*) stopId;
- (VehiclePositionBuilder*) setStopId:(NSString*) value;
- (VehiclePositionBuilder*) clearStopId;

- (BOOL) hasCurrentStatus;
- (VehiclePositionVehicleStopStatus) currentStatus;
- (VehiclePositionBuilder*) setCurrentStatus:(VehiclePositionVehicleStopStatus) value;
- (VehiclePositionBuilder*) clearCurrentStatus;

- (BOOL) hasTimestamp;
- (UInt64) timestamp;
- (VehiclePositionBuilder*) setTimestamp:(UInt64) value;
- (VehiclePositionBuilder*) clearTimestamp;

- (BOOL) hasCongestionLevel;
- (VehiclePositionCongestionLevel) congestionLevel;
- (VehiclePositionBuilder*) setCongestionLevel:(VehiclePositionCongestionLevel) value;
- (VehiclePositionBuilder*) clearCongestionLevel;

- (BOOL) hasOccupancyStatus;
- (VehiclePositionOccupancyStatus) occupancyStatus;
- (VehiclePositionBuilder*) setOccupancyStatus:(VehiclePositionOccupancyStatus) value;
- (VehiclePositionBuilder*) clearOccupancyStatus;
@end

#define Alert_active_period @"activePeriod"
#define Alert_informed_entity @"informedEntity"
#define Alert_cause @"cause"
#define Alert_effect @"effect"
#define Alert_url @"url"
#define Alert_header_text @"headerText"
#define Alert_description_text @"descriptionText"
@interface Alert : PBExtendableMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUrl_:1;
  BOOL hasHeaderText_:1;
  BOOL hasDescriptionText_:1;
  BOOL hasCause_:1;
  BOOL hasEffect_:1;
  TranslatedString* url;
  TranslatedString* headerText;
  TranslatedString* descriptionText;
  AlertCause cause;
  AlertEffect effect;
  NSMutableArray * activePeriodArray;
  NSMutableArray * informedEntityArray;
}
- (BOOL) hasCause;
- (BOOL) hasEffect;
- (BOOL) hasUrl;
- (BOOL) hasHeaderText;
- (BOOL) hasDescriptionText;
@property (readonly, strong) NSArray * activePeriod;
@property (readonly, strong) NSArray * informedEntity;
@property (readonly) AlertCause cause;
@property (readonly) AlertEffect effect;
@property (readonly, strong) TranslatedString* url;
@property (readonly, strong) TranslatedString* headerText;
@property (readonly, strong) TranslatedString* descriptionText;
- (TimeRange*)activePeriodAtIndex:(NSUInteger)index;
- (EntitySelector*)informedEntityAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (AlertBuilder*) builder;
+ (AlertBuilder*) builder;
+ (AlertBuilder*) builderWithPrototype:(Alert*) prototype;
- (AlertBuilder*) toBuilder;

+ (Alert*) parseFromData:(NSData*) data;
+ (Alert*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Alert*) parseFromInputStream:(NSInputStream*) input;
+ (Alert*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Alert*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Alert*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface AlertBuilder : PBExtendableMessageBuilder {
@private
  Alert* resultAlert;
}

- (Alert*) defaultInstance;

- (AlertBuilder*) clear;
- (AlertBuilder*) clone;

- (Alert*) build;
- (Alert*) buildPartial;

- (AlertBuilder*) mergeFrom:(Alert*) other;
- (AlertBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (AlertBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSMutableArray *)activePeriod;
- (TimeRange*)activePeriodAtIndex:(NSUInteger)index;
- (AlertBuilder *)addActivePeriod:(TimeRange*)value;
- (AlertBuilder *)setActivePeriodArray:(NSArray *)array;
- (AlertBuilder *)clearActivePeriod;

- (NSMutableArray *)informedEntity;
- (EntitySelector*)informedEntityAtIndex:(NSUInteger)index;
- (AlertBuilder *)addInformedEntity:(EntitySelector*)value;
- (AlertBuilder *)setInformedEntityArray:(NSArray *)array;
- (AlertBuilder *)clearInformedEntity;

- (BOOL) hasCause;
- (AlertCause) cause;
- (AlertBuilder*) setCause:(AlertCause) value;
- (AlertBuilder*) clearCause;

- (BOOL) hasEffect;
- (AlertEffect) effect;
- (AlertBuilder*) setEffect:(AlertEffect) value;
- (AlertBuilder*) clearEffect;

- (BOOL) hasUrl;
- (TranslatedString*) url;
- (AlertBuilder*) setUrl:(TranslatedString*) value;
- (AlertBuilder*) setUrlBuilder:(TranslatedStringBuilder*) builderForValue;
- (AlertBuilder*) mergeUrl:(TranslatedString*) value;
- (AlertBuilder*) clearUrl;

- (BOOL) hasHeaderText;
- (TranslatedString*) headerText;
- (AlertBuilder*) setHeaderText:(TranslatedString*) value;
- (AlertBuilder*) setHeaderTextBuilder:(TranslatedStringBuilder*) builderForValue;
- (AlertBuilder*) mergeHeaderText:(TranslatedString*) value;
- (AlertBuilder*) clearHeaderText;

- (BOOL) hasDescriptionText;
- (TranslatedString*) descriptionText;
- (AlertBuilder*) setDescriptionText:(TranslatedString*) value;
- (AlertBuilder*) setDescriptionTextBuilder:(TranslatedStringBuilder*) builderForValue;
- (AlertBuilder*) mergeDescriptionText:(TranslatedString*) value;
- (AlertBuilder*) clearDescriptionText;
@end

#define TimeRange_start @"start"
#define TimeRange_end @"end"
@interface TimeRange : PBExtendableMessage<GeneratedMessageProtocol> {
@private
  BOOL hasStart_:1;
  BOOL hasEnd_:1;
  UInt64 start;
  UInt64 end;
}
- (BOOL) hasStart;
- (BOOL) hasEnd;
@property (readonly) UInt64 start;
@property (readonly) UInt64 end;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (TimeRangeBuilder*) builder;
+ (TimeRangeBuilder*) builder;
+ (TimeRangeBuilder*) builderWithPrototype:(TimeRange*) prototype;
- (TimeRangeBuilder*) toBuilder;

+ (TimeRange*) parseFromData:(NSData*) data;
+ (TimeRange*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TimeRange*) parseFromInputStream:(NSInputStream*) input;
+ (TimeRange*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TimeRange*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (TimeRange*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface TimeRangeBuilder : PBExtendableMessageBuilder {
@private
  TimeRange* resultTimeRange;
}

- (TimeRange*) defaultInstance;

- (TimeRangeBuilder*) clear;
- (TimeRangeBuilder*) clone;

- (TimeRange*) build;
- (TimeRange*) buildPartial;

- (TimeRangeBuilder*) mergeFrom:(TimeRange*) other;
- (TimeRangeBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (TimeRangeBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasStart;
- (UInt64) start;
- (TimeRangeBuilder*) setStart:(UInt64) value;
- (TimeRangeBuilder*) clearStart;

- (BOOL) hasEnd;
- (UInt64) end;
- (TimeRangeBuilder*) setEnd:(UInt64) value;
- (TimeRangeBuilder*) clearEnd;
@end

#define Position_latitude @"latitude"
#define Position_longitude @"longitude"
#define Position_bearing @"bearing"
#define Position_odometer @"odometer"
#define Position_speed @"speed"
@interface Position : PBExtendableMessage<GeneratedMessageProtocol> {
@private
  BOOL hasOdometer_:1;
  BOOL hasLatitude_:1;
  BOOL hasLongitude_:1;
  BOOL hasBearing_:1;
  BOOL hasSpeed_:1;
  Float64 odometer;
  Float32 latitude;
  Float32 longitude;
  Float32 bearing;
  Float32 speed;
}
- (BOOL) hasLatitude;
- (BOOL) hasLongitude;
- (BOOL) hasBearing;
- (BOOL) hasOdometer;
- (BOOL) hasSpeed;
@property (readonly) Float32 latitude;
@property (readonly) Float32 longitude;
@property (readonly) Float32 bearing;
@property (readonly) Float64 odometer;
@property (readonly) Float32 speed;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PositionBuilder*) builder;
+ (PositionBuilder*) builder;
+ (PositionBuilder*) builderWithPrototype:(Position*) prototype;
- (PositionBuilder*) toBuilder;

+ (Position*) parseFromData:(NSData*) data;
+ (Position*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Position*) parseFromInputStream:(NSInputStream*) input;
+ (Position*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Position*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Position*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PositionBuilder : PBExtendableMessageBuilder {
@private
  Position* resultPosition;
}

- (Position*) defaultInstance;

- (PositionBuilder*) clear;
- (PositionBuilder*) clone;

- (Position*) build;
- (Position*) buildPartial;

- (PositionBuilder*) mergeFrom:(Position*) other;
- (PositionBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PositionBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasLatitude;
- (Float32) latitude;
- (PositionBuilder*) setLatitude:(Float32) value;
- (PositionBuilder*) clearLatitude;

- (BOOL) hasLongitude;
- (Float32) longitude;
- (PositionBuilder*) setLongitude:(Float32) value;
- (PositionBuilder*) clearLongitude;

- (BOOL) hasBearing;
- (Float32) bearing;
- (PositionBuilder*) setBearing:(Float32) value;
- (PositionBuilder*) clearBearing;

- (BOOL) hasOdometer;
- (Float64) odometer;
- (PositionBuilder*) setOdometer:(Float64) value;
- (PositionBuilder*) clearOdometer;

- (BOOL) hasSpeed;
- (Float32) speed;
- (PositionBuilder*) setSpeed:(Float32) value;
- (PositionBuilder*) clearSpeed;
@end

#define TripDescriptor_trip_id @"tripId"
#define TripDescriptor_route_id @"routeId"
#define TripDescriptor_direction_id @"directionId"
#define TripDescriptor_start_time @"startTime"
#define TripDescriptor_start_date @"startDate"
#define TripDescriptor_schedule_relationship @"scheduleRelationship"
@interface TripDescriptor : PBExtendableMessage<GeneratedMessageProtocol> {
@private
  BOOL hasTripId_:1;
  BOOL hasRouteId_:1;
  BOOL hasStartTime_:1;
  BOOL hasStartDate_:1;
  BOOL hasDirectionId_:1;
  BOOL hasScheduleRelationship_:1;
  NSString* tripId;
  NSString* routeId;
  NSString* startTime;
  NSString* startDate;
  UInt32 directionId;
  TripDescriptorScheduleRelationship scheduleRelationship;
}
- (BOOL) hasTripId;
- (BOOL) hasRouteId;
- (BOOL) hasDirectionId;
- (BOOL) hasStartTime;
- (BOOL) hasStartDate;
- (BOOL) hasScheduleRelationship;
@property (readonly, strong) NSString* tripId;
@property (readonly, strong) NSString* routeId;
@property (readonly) UInt32 directionId;
@property (readonly, strong) NSString* startTime;
@property (readonly, strong) NSString* startDate;
@property (readonly) TripDescriptorScheduleRelationship scheduleRelationship;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (TripDescriptorBuilder*) builder;
+ (TripDescriptorBuilder*) builder;
+ (TripDescriptorBuilder*) builderWithPrototype:(TripDescriptor*) prototype;
- (TripDescriptorBuilder*) toBuilder;

+ (TripDescriptor*) parseFromData:(NSData*) data;
+ (TripDescriptor*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TripDescriptor*) parseFromInputStream:(NSInputStream*) input;
+ (TripDescriptor*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TripDescriptor*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (TripDescriptor*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface TripDescriptorBuilder : PBExtendableMessageBuilder {
@private
  TripDescriptor* resultTripDescriptor;
}

- (TripDescriptor*) defaultInstance;

- (TripDescriptorBuilder*) clear;
- (TripDescriptorBuilder*) clone;

- (TripDescriptor*) build;
- (TripDescriptor*) buildPartial;

- (TripDescriptorBuilder*) mergeFrom:(TripDescriptor*) other;
- (TripDescriptorBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (TripDescriptorBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasTripId;
- (NSString*) tripId;
- (TripDescriptorBuilder*) setTripId:(NSString*) value;
- (TripDescriptorBuilder*) clearTripId;

- (BOOL) hasRouteId;
- (NSString*) routeId;
- (TripDescriptorBuilder*) setRouteId:(NSString*) value;
- (TripDescriptorBuilder*) clearRouteId;

- (BOOL) hasDirectionId;
- (UInt32) directionId;
- (TripDescriptorBuilder*) setDirectionId:(UInt32) value;
- (TripDescriptorBuilder*) clearDirectionId;

- (BOOL) hasStartTime;
- (NSString*) startTime;
- (TripDescriptorBuilder*) setStartTime:(NSString*) value;
- (TripDescriptorBuilder*) clearStartTime;

- (BOOL) hasStartDate;
- (NSString*) startDate;
- (TripDescriptorBuilder*) setStartDate:(NSString*) value;
- (TripDescriptorBuilder*) clearStartDate;

- (BOOL) hasScheduleRelationship;
- (TripDescriptorScheduleRelationship) scheduleRelationship;
- (TripDescriptorBuilder*) setScheduleRelationship:(TripDescriptorScheduleRelationship) value;
- (TripDescriptorBuilder*) clearScheduleRelationship;
@end

#define VehicleDescriptor_id @"id"
#define VehicleDescriptor_label @"label"
#define VehicleDescriptor_license_plate @"licensePlate"
@interface VehicleDescriptor : PBExtendableMessage<GeneratedMessageProtocol> {
@private
  BOOL hasId_:1;
  BOOL hasLabel_:1;
  BOOL hasLicensePlate_:1;
  NSString* id;
  NSString* label;
  NSString* licensePlate;
}
- (BOOL) hasId;
- (BOOL) hasLabel;
- (BOOL) hasLicensePlate;
@property (readonly, strong) NSString* id;
@property (readonly, strong) NSString* label;
@property (readonly, strong) NSString* licensePlate;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (VehicleDescriptorBuilder*) builder;
+ (VehicleDescriptorBuilder*) builder;
+ (VehicleDescriptorBuilder*) builderWithPrototype:(VehicleDescriptor*) prototype;
- (VehicleDescriptorBuilder*) toBuilder;

+ (VehicleDescriptor*) parseFromData:(NSData*) data;
+ (VehicleDescriptor*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (VehicleDescriptor*) parseFromInputStream:(NSInputStream*) input;
+ (VehicleDescriptor*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (VehicleDescriptor*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (VehicleDescriptor*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface VehicleDescriptorBuilder : PBExtendableMessageBuilder {
@private
  VehicleDescriptor* resultVehicleDescriptor;
}

- (VehicleDescriptor*) defaultInstance;

- (VehicleDescriptorBuilder*) clear;
- (VehicleDescriptorBuilder*) clone;

- (VehicleDescriptor*) build;
- (VehicleDescriptor*) buildPartial;

- (VehicleDescriptorBuilder*) mergeFrom:(VehicleDescriptor*) other;
- (VehicleDescriptorBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (VehicleDescriptorBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (NSString*) id;
- (VehicleDescriptorBuilder*) setId:(NSString*) value;
- (VehicleDescriptorBuilder*) clearId;

- (BOOL) hasLabel;
- (NSString*) label;
- (VehicleDescriptorBuilder*) setLabel:(NSString*) value;
- (VehicleDescriptorBuilder*) clearLabel;

- (BOOL) hasLicensePlate;
- (NSString*) licensePlate;
- (VehicleDescriptorBuilder*) setLicensePlate:(NSString*) value;
- (VehicleDescriptorBuilder*) clearLicensePlate;
@end

#define EntitySelector_agency_id @"agencyId"
#define EntitySelector_route_id @"routeId"
#define EntitySelector_route_type @"routeType"
#define EntitySelector_trip @"trip"
#define EntitySelector_stop_id @"stopId"
@interface EntitySelector : PBExtendableMessage<GeneratedMessageProtocol> {
@private
  BOOL hasRouteType_:1;
  BOOL hasAgencyId_:1;
  BOOL hasRouteId_:1;
  BOOL hasStopId_:1;
  BOOL hasTrip_:1;
  SInt32 routeType;
  NSString* agencyId;
  NSString* routeId;
  NSString* stopId;
  TripDescriptor* trip;
}
- (BOOL) hasAgencyId;
- (BOOL) hasRouteId;
- (BOOL) hasRouteType;
- (BOOL) hasTrip;
- (BOOL) hasStopId;
@property (readonly, strong) NSString* agencyId;
@property (readonly, strong) NSString* routeId;
@property (readonly) SInt32 routeType;
@property (readonly, strong) TripDescriptor* trip;
@property (readonly, strong) NSString* stopId;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (EntitySelectorBuilder*) builder;
+ (EntitySelectorBuilder*) builder;
+ (EntitySelectorBuilder*) builderWithPrototype:(EntitySelector*) prototype;
- (EntitySelectorBuilder*) toBuilder;

+ (EntitySelector*) parseFromData:(NSData*) data;
+ (EntitySelector*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (EntitySelector*) parseFromInputStream:(NSInputStream*) input;
+ (EntitySelector*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (EntitySelector*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (EntitySelector*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface EntitySelectorBuilder : PBExtendableMessageBuilder {
@private
  EntitySelector* resultEntitySelector;
}

- (EntitySelector*) defaultInstance;

- (EntitySelectorBuilder*) clear;
- (EntitySelectorBuilder*) clone;

- (EntitySelector*) build;
- (EntitySelector*) buildPartial;

- (EntitySelectorBuilder*) mergeFrom:(EntitySelector*) other;
- (EntitySelectorBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (EntitySelectorBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasAgencyId;
- (NSString*) agencyId;
- (EntitySelectorBuilder*) setAgencyId:(NSString*) value;
- (EntitySelectorBuilder*) clearAgencyId;

- (BOOL) hasRouteId;
- (NSString*) routeId;
- (EntitySelectorBuilder*) setRouteId:(NSString*) value;
- (EntitySelectorBuilder*) clearRouteId;

- (BOOL) hasRouteType;
- (SInt32) routeType;
- (EntitySelectorBuilder*) setRouteType:(SInt32) value;
- (EntitySelectorBuilder*) clearRouteType;

- (BOOL) hasTrip;
- (TripDescriptor*) trip;
- (EntitySelectorBuilder*) setTrip:(TripDescriptor*) value;
- (EntitySelectorBuilder*) setTripBuilder:(TripDescriptorBuilder*) builderForValue;
- (EntitySelectorBuilder*) mergeTrip:(TripDescriptor*) value;
- (EntitySelectorBuilder*) clearTrip;

- (BOOL) hasStopId;
- (NSString*) stopId;
- (EntitySelectorBuilder*) setStopId:(NSString*) value;
- (EntitySelectorBuilder*) clearStopId;
@end

#define TranslatedString_translation @"translation"
@interface TranslatedString : PBExtendableMessage<GeneratedMessageProtocol> {
@private
  NSMutableArray * translationArray;
}
@property (readonly, strong) NSArray * translation;
- (TranslatedStringTranslation*)translationAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (TranslatedStringBuilder*) builder;
+ (TranslatedStringBuilder*) builder;
+ (TranslatedStringBuilder*) builderWithPrototype:(TranslatedString*) prototype;
- (TranslatedStringBuilder*) toBuilder;

+ (TranslatedString*) parseFromData:(NSData*) data;
+ (TranslatedString*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TranslatedString*) parseFromInputStream:(NSInputStream*) input;
+ (TranslatedString*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TranslatedString*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (TranslatedString*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

#define Translation_text @"text"
#define Translation_language @"language"
@interface TranslatedStringTranslation : PBExtendableMessage<GeneratedMessageProtocol> {
@private
  BOOL hasText_:1;
  BOOL hasLanguage_:1;
  NSString* text;
  NSString* language;
}
- (BOOL) hasText;
- (BOOL) hasLanguage;
@property (readonly, strong) NSString* text;
@property (readonly, strong) NSString* language;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (TranslatedStringTranslationBuilder*) builder;
+ (TranslatedStringTranslationBuilder*) builder;
+ (TranslatedStringTranslationBuilder*) builderWithPrototype:(TranslatedStringTranslation*) prototype;
- (TranslatedStringTranslationBuilder*) toBuilder;

+ (TranslatedStringTranslation*) parseFromData:(NSData*) data;
+ (TranslatedStringTranslation*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TranslatedStringTranslation*) parseFromInputStream:(NSInputStream*) input;
+ (TranslatedStringTranslation*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TranslatedStringTranslation*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (TranslatedStringTranslation*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface TranslatedStringTranslationBuilder : PBExtendableMessageBuilder {
@private
  TranslatedStringTranslation* resultTranslation;
}

- (TranslatedStringTranslation*) defaultInstance;

- (TranslatedStringTranslationBuilder*) clear;
- (TranslatedStringTranslationBuilder*) clone;

- (TranslatedStringTranslation*) build;
- (TranslatedStringTranslation*) buildPartial;

- (TranslatedStringTranslationBuilder*) mergeFrom:(TranslatedStringTranslation*) other;
- (TranslatedStringTranslationBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (TranslatedStringTranslationBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasText;
- (NSString*) text;
- (TranslatedStringTranslationBuilder*) setText:(NSString*) value;
- (TranslatedStringTranslationBuilder*) clearText;

- (BOOL) hasLanguage;
- (NSString*) language;
- (TranslatedStringTranslationBuilder*) setLanguage:(NSString*) value;
- (TranslatedStringTranslationBuilder*) clearLanguage;
@end

@interface TranslatedStringBuilder : PBExtendableMessageBuilder {
@private
  TranslatedString* resultTranslatedString;
}

- (TranslatedString*) defaultInstance;

- (TranslatedStringBuilder*) clear;
- (TranslatedStringBuilder*) clone;

- (TranslatedString*) build;
- (TranslatedString*) buildPartial;

- (TranslatedStringBuilder*) mergeFrom:(TranslatedString*) other;
- (TranslatedStringBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (TranslatedStringBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSMutableArray *)translation;
- (TranslatedStringTranslation*)translationAtIndex:(NSUInteger)index;
- (TranslatedStringBuilder *)addTranslation:(TranslatedStringTranslation*)value;
- (TranslatedStringBuilder *)setTranslationArray:(NSArray *)array;
- (TranslatedStringBuilder *)clearTranslation;
@end


// @@protoc_insertion_point(global_scope)
